# Generated by Django 3.1 on 2023-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
    ]
