# Generated by Django 3.1 on 2023-12-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pin_code',
        ),
    ]
